version: '3.4'

networks:
  deploy-guide-dev:
    driver: bridge

services:
  moscowarts:
    container_name: deploy-guide
    image: ${DOCKER_REGISTRY-}moscowarts
    build:
      context: .
      dockerfile: MoscowArts/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres_db
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kostylygin2004
      POSTGRES_DB: MoscowArts
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: